package cn.cdjzxy.android.monitoringassistant.mvp.model.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.cdjzxy.android.monitoringassistant.mvp.model.entity.sampling.Form;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FORM".
*/
public class FormDao extends AbstractDao<Form, Void> {

    public static final String TABLENAME = "FORM";

    /**
     * Properties of entity Form.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property TagId = new Property(0, String.class, "TagId", false, "TAG_ID");
        public final static Property TagName = new Property(1, String.class, "TagName", false, "TAG_NAME");
    }


    public FormDao(DaoConfig config) {
        super(config);
    }
    
    public FormDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FORM\" (" + //
                "\"TAG_ID\" TEXT," + // 0: TagId
                "\"TAG_NAME\" TEXT);"); // 1: TagName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FORM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Form entity) {
        stmt.clearBindings();
 
        String TagId = entity.getTagId();
        if (TagId != null) {
            stmt.bindString(1, TagId);
        }
 
        String TagName = entity.getTagName();
        if (TagName != null) {
            stmt.bindString(2, TagName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Form entity) {
        stmt.clearBindings();
 
        String TagId = entity.getTagId();
        if (TagId != null) {
            stmt.bindString(1, TagId);
        }
 
        String TagName = entity.getTagName();
        if (TagName != null) {
            stmt.bindString(2, TagName);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Form readEntity(Cursor cursor, int offset) {
        Form entity = new Form( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // TagId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // TagName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Form entity, int offset) {
        entity.setTagId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTagName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Form entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Form entity) {
        return null;
    }

    @Override
    public boolean hasKey(Form entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
