package cn.cdjzxy.android.monitoringassistant.mvp.model.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.cdjzxy.android.monitoringassistant.mvp.model.entity.project.ProjectContent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PROJECT_CONTENT".
*/
public class ProjectContentDao extends AbstractDao<ProjectContent, String> {

    public static final String TABLENAME = "PROJECT_CONTENT";

    /**
     * Properties of entity ProjectContent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "Id", true, "ID");
        public final static Property ProjectId = new Property(1, String.class, "ProjectId", false, "PROJECT_ID");
        public final static Property UpdateTime = new Property(2, String.class, "UpdateTime", false, "UPDATE_TIME");
        public final static Property TagId = new Property(3, String.class, "TagId", false, "TAG_ID");
        public final static Property TagName = new Property(4, String.class, "TagName", false, "TAG_NAME");
        public final static Property AddressIds = new Property(5, String.class, "AddressIds", false, "ADDRESS_IDS");
        public final static Property Address = new Property(6, String.class, "Address", false, "ADDRESS");
        public final static Property TagParentId = new Property(7, String.class, "TagParentId", false, "TAG_PARENT_ID");
        public final static Property TagParentName = new Property(8, String.class, "TagParentName", false, "TAG_PARENT_NAME");
        public final static Property Days = new Property(9, int.class, "Days", false, "DAYS");
        public final static Property Period = new Property(10, int.class, "Period", false, "PERIOD");
    }


    public ProjectContentDao(DaoConfig config) {
        super(config);
    }
    
    public ProjectContentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PROJECT_CONTENT\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: Id
                "\"PROJECT_ID\" TEXT," + // 1: ProjectId
                "\"UPDATE_TIME\" TEXT," + // 2: UpdateTime
                "\"TAG_ID\" TEXT," + // 3: TagId
                "\"TAG_NAME\" TEXT," + // 4: TagName
                "\"ADDRESS_IDS\" TEXT," + // 5: AddressIds
                "\"ADDRESS\" TEXT," + // 6: Address
                "\"TAG_PARENT_ID\" TEXT," + // 7: TagParentId
                "\"TAG_PARENT_NAME\" TEXT," + // 8: TagParentName
                "\"DAYS\" INTEGER NOT NULL ," + // 9: Days
                "\"PERIOD\" INTEGER NOT NULL );"); // 10: Period
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PROJECT_CONTENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ProjectContent entity) {
        stmt.clearBindings();
 
        String Id = entity.getId();
        if (Id != null) {
            stmt.bindString(1, Id);
        }
 
        String ProjectId = entity.getProjectId();
        if (ProjectId != null) {
            stmt.bindString(2, ProjectId);
        }
 
        String UpdateTime = entity.getUpdateTime();
        if (UpdateTime != null) {
            stmt.bindString(3, UpdateTime);
        }
 
        String TagId = entity.getTagId();
        if (TagId != null) {
            stmt.bindString(4, TagId);
        }
 
        String TagName = entity.getTagName();
        if (TagName != null) {
            stmt.bindString(5, TagName);
        }
 
        String AddressIds = entity.getAddressIds();
        if (AddressIds != null) {
            stmt.bindString(6, AddressIds);
        }
 
        String Address = entity.getAddress();
        if (Address != null) {
            stmt.bindString(7, Address);
        }
 
        String TagParentId = entity.getTagParentId();
        if (TagParentId != null) {
            stmt.bindString(8, TagParentId);
        }
 
        String TagParentName = entity.getTagParentName();
        if (TagParentName != null) {
            stmt.bindString(9, TagParentName);
        }
        stmt.bindLong(10, entity.getDays());
        stmt.bindLong(11, entity.getPeriod());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ProjectContent entity) {
        stmt.clearBindings();
 
        String Id = entity.getId();
        if (Id != null) {
            stmt.bindString(1, Id);
        }
 
        String ProjectId = entity.getProjectId();
        if (ProjectId != null) {
            stmt.bindString(2, ProjectId);
        }
 
        String UpdateTime = entity.getUpdateTime();
        if (UpdateTime != null) {
            stmt.bindString(3, UpdateTime);
        }
 
        String TagId = entity.getTagId();
        if (TagId != null) {
            stmt.bindString(4, TagId);
        }
 
        String TagName = entity.getTagName();
        if (TagName != null) {
            stmt.bindString(5, TagName);
        }
 
        String AddressIds = entity.getAddressIds();
        if (AddressIds != null) {
            stmt.bindString(6, AddressIds);
        }
 
        String Address = entity.getAddress();
        if (Address != null) {
            stmt.bindString(7, Address);
        }
 
        String TagParentId = entity.getTagParentId();
        if (TagParentId != null) {
            stmt.bindString(8, TagParentId);
        }
 
        String TagParentName = entity.getTagParentName();
        if (TagParentName != null) {
            stmt.bindString(9, TagParentName);
        }
        stmt.bindLong(10, entity.getDays());
        stmt.bindLong(11, entity.getPeriod());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public ProjectContent readEntity(Cursor cursor, int offset) {
        ProjectContent entity = new ProjectContent( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // Id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // ProjectId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // UpdateTime
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // TagId
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // TagName
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // AddressIds
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // Address
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // TagParentId
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // TagParentName
            cursor.getInt(offset + 9), // Days
            cursor.getInt(offset + 10) // Period
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ProjectContent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setProjectId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUpdateTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTagId(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTagName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setAddressIds(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setAddress(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTagParentId(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setTagParentName(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setDays(cursor.getInt(offset + 9));
        entity.setPeriod(cursor.getInt(offset + 10));
     }
    
    @Override
    protected final String updateKeyAfterInsert(ProjectContent entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(ProjectContent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ProjectContent entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
